### ISSUE TITLE
Column 'width' cannot be null

### ISSUE THREAD

**Issue by myspulin** [forkcms/fork-cms-module-media-library#29]
Hello,

I have installed your module, installation was successful without any error. When I tried to add some zip file I got these errors:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'height' cannot be null
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'width' cannot be null

After changing these columns to be nullable the sql query works as expected, data was inserted.

Could you please update these columns to nullable or change the default value?

Thank you!

Regards Lukas

**Comment by jeroendesloovere** [comment]
Hi Lukas,

I'll look into this.

I'm currently refactoring this module in [this branch](https://github.com/forkcms/fork-cms-module-media-library/tree/refactoring-to-symfony-form). When finished, the module will work with Symfony form!

**Comment by myspulin** [comment]
Hi Jeroen,

cool, looking forward to check the new version! Thank you.
