### ISSUE TITLE
Missing constraints after installation

### ISSUE THREAD

**Issue by myspulin** [forkcms/fork-cms-module-media-library#34]
Hi,

after installation of the module and issuing command: php app/console doctrine:schema:update --dump-sql I have got these sqls:

ALTER TABLE mediagroupmediaitem ADD CONSTRAINT FK_BCC51AD86776CC71 FOREIGN KEY (
mediaGroupId) REFERENCES MediaGroup (id) ON DELETE CASCADE;
ALTER TABLE mediagroupmediaitem ADD CONSTRAINT FK_BCC51AD827759A6A FOREIGN KEY (
mediaItemId) REFERENCES MediaItem (id) ON DELETE CASCADE;
ALTER TABLE mediaitem ADD CONSTRAINT FK_3BE26384C1DCBB95 FOREIGN KEY (mediaFolde
rId) REFERENCES MediaFolder (id) ON DELETE CASCADE;

All constraints was not created during the installation, could you please check why is that?

Thank you!

**Comment by carakas** [comment]
@myspulin can you recreate this issue on http://github.com/forkcms/forkcms ?
It has nothing to do with this module but is a general issue

**Comment by myspulin** [comment]
Sure, no problem. Thanks.

**Comment by jeroendesloovere** [comment]
Hi @myspulin,
would be nice if you can give me some feedback on the MediaLibrary module.
Did everything work, are you missing some things, ...

You can chat with most of the Fork CMS developers on
https://fork-cms.herokuapp.com
